version: 2
updates:
    -   package-ecosystem: composer
        directory: /
        schedule:
            interval: daily
            time: '05:30'
            timezone: Europe/Bratislava
        pull-request-branch-name:
            separator: '-'
        open-pull-requests-limit: 99